name: Build and deploy ASP.Net Core app to Azure Web App - pbmatshumba

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore NutriPlan.csproj

      - name: Build with dotnet
        run: dotnet build NutriPlan.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish NutriPlan.csproj -c Release -o ${{env.DOTNET_ROOT}}

      - name: List contents of the publish directory
        run: dir ./myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C9BEF40CD9664B5F9E77DBB8D944D939 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EA86BF8151744ACF94F29E5AAF1F9E65 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CED030F64E7540878BF5F3DF0AD6EFBB }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pbmatshumba'
          slot-name: 'Production'
          package: .  # Ensure this matches the output directory from publish
