name: Build, Deploy, and Migrate ASP.NET Core app to Azure Web App - pbmatshumba

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Display .NET information
        run: |
          dotnet --info
          dotnet --version

      - name: List directory contents
        run: |
          dir
          dir /s *.csproj

      - name: Install dotnet-ef tool
        run: dotnet tool install --global dotnet-ef

      - name: Restore NuGet packages
        run: dotnet restore
        
      - name: Build with dotnet
        run: dotnet build --configuration Release -v d

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal

      - name: dotnet publish
        if: success()
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp" -v d

      - name: Upload artifact for deployment job
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy-and-migrate:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C9BEF40CD9664B5F9E77DBB8D944D939 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EA86BF8151744ACF94F29E5AAF1F9E65 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CED030F64E7540878BF5F3DF0AD6EFBB }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pbmatshumba'
          slot-name: 'Production'
          package: ${{env.DOTNET_ROOT}}/myapp

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install dotnet-ef tool
        run: dotnet tool install --global dotnet-ef

      - name: List directory contents
        run: |
          dir
          dir /s *.csproj

      - name: Run database migrations
        run: |
          $env:PATH += ";$env:USERPROFILE\.dotnet\tools"
          dotnet ef database update --verbose
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
          ASPNETCORE_ENVIRONMENT: Production
          ConnectionStrings__DefaultConnection: ${{ secrets.AZURE_DATABASE_CONNECTION_STRING }}